# -*- coding: utf-8 -*-
"""altura_ola_2m.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7ILQU1ao3r9G446sGSxGpWmomSaVqZR
"""

import math as mt

# Parámetros iniciales

Lo = (9.81*T**2)/(2*mt.pi)
#print(Lo)
T = 11.63
d=2 # Canviar la profunditat depen el que vulgui comprovar :)

# Valor inicial para U_G

Ld2m = Lo
tolerancia = 1e-9  # Criterio de convergencia
max_iter = 100000  # Número máximo de iteraciones

# Iteración

for i in range(max_iter):
    nuevo_L1 = (9.81*T**2)/(2*mt.pi)*mt.tanh((2*mt.pi)*d/Ld2m)

    # Check if nuevo_L1 is too large before assigning to Ld2m
    if nuevo_L1 > 1e100:  # Or another suitable threshold
        print("Divergencia: El valor de Ld2m se está volviendo demasiado grande.")
        break  # Exit the loop to prevent OverflowError

    #print(f"Diferencia {nuevo_L1-Ld2m}") # Para ver los valores de diferencia


    if abs(nuevo_L1 - Ld2m) < tolerancia:  # Condición de convergencia
        break
    Ld2m = nuevo_L1

# Resultado

print(f"Convergencia alcanzada después de {i+1} iteraciones: Ld2m = {Ld2m:.6f}")